### ISSUE TITLE
Urgent need for datasets

### ISSUE THREAD

**Issue by pandeyAayush** [Leminhbinh0209/CVPR24-FAS#3]
First of all, huge congratulations on your work. It's really impressive.

Coming to the issue, I came across your work only recently & need to reproduce the results on an urgent basis. I've everything setup (thanks to the comprehensive codebase), except gathering the dsets. I've been trying but couldn't find them online. It'll be an immense help if you can help me out here, by pointing to the source from where I can get them quickly. 

Thanks a lot in advance!

**Comment by Leminhbinh0209** [comment]
This is unofficial but I gather from other repositories's discussions:
 - OULU:  https://pan.baidu.com/s/1frIxdpb1Vg_5c2c8fjgSmA?pwd=qli4#list/path=%2F , see the discussion her https://github.com/ZitongYu/CDCN/issues/29
- CASIA-FASD:  https://pan.baidu.com/s/15HyX7tizCCuwN9BKiV9_zA Password: h5un, see discussion https://github.com/mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing/issues/5
- Idiap replay attack: apply for the dataset here: https://www.idiap.ch/en/scientific-research/data/replayattack, it need author agreement
-

**Comment by pandeyAayush** [comment]
Thanks a lot for your prompt help. I'll try download the dsets and move ahead with reproducing the results.
